# simulator/configs/full_87.yaml
start_date: "2025-01-01"
end_date: "2025-12-31"
seed: 7
initial_regime: "sideways"
output_dir: "data/market"

# Universe (your 87 tickers)
universe:
  - AAPL
  - TSLA
  - AMZN
  - MSFT
  - NVDA
  - GOOGL
  - META
  - NFLX
  - JPM
  - V
  - BAC
  - PYPL
  - DIS
  - T
  - PFE
  - COST
  - INTC
  - KO
  - TGT
  - NKE
  - SPY
  - BA
  - BABA
  - XOM
  - WMT
  - GE
  - CSCO
  - VZ
  - JNJ
  - CVX
  - PLTR
  - SQ
  - SHOP
  - SBUX
  - SOFI
  - HOOD
  - RBLX
  - SNAP
  - AMD
  - UBER
  - FDX
  - ABBV
  - ETSY
  - MRNA
  - LMT
  - GM
  - F
  - LCID
  - CCL
  - DAL
  - UAL
  - AAL
  - TSM
  - SONY
  - ET
  - MRO
  - COIN
  - RIVN
  - RIOT
  - CPRX
  - VWO
  - SPYG
  - NOK
  - ROKU
  - VIAC
  - ATVI
  - BIDU
  - DOCU
  - ZM
  - PINS
  - TLRY
  - WBA
  - MGM
  - NIO
  - C
  - GS
  - WFC
  - ADBE
  - PEP
  - UNH
  - CARR
  - HCA
  - TWTR
  - BILI
  - SIRI
  - FUBO
  - RKT
